### ISSUE TITLE
Delphi + Python

### ISSUE THREAD

**Issue by kazuser** [Embarcadero/Lightweight-Python-Wrappers#18]
Hi there! I think I need your help :)

Installed everything (Lightweight-Python-Wrappers + python4delphi + PythonEnviroments) and everything works fine (btw, thanks a lot!). But now I need to install/connect/integrate https://github.com/jsvine/pdfplumber somehow — what next? 😶

![1](https://github.com/Embarcadero/Lightweight-Python-Wrappers/assets/3335273/04d09a26-067c-4bc3-821b-272d8c6ce9e9)

[test.zip](https://github.com/Embarcadero/Lightweight-Python-Wrappers/files/11798998/test.zip)

**Comment by lmbelo** [comment]
Have a close look at [DSC](https://github.com/Embarcadero/P4D-Data-Sciences) components, it will be helpful.
Let me know if you need something else.

**Comment by kazuser** [comment]
![image](https://github.com/Embarcadero/Lightweight-Python-Wrappers/assets/3335273/67ace0a4-ffdf-44ae-90f8-a7d80545e66a)

Yes, thank you, I already have it, but I don't understand your main magic — how do you convert Python libraries to Delphi components 😕

**Comment by kazuser** [comment]
![image](https://github.com/Embarcadero/Lightweight-Python-Wrappers/assets/3335273/1508ea5f-b8b0-4928-b7ef-1605d32a1e94)

Wait a minute. All these selected files created manually, right? 🥲

**Comment by lmbelo** [comment]
@kazuser yes, right. You can use the NLTK.pas as a suggestion to yours.
There is an app to automagically create these comps too. Hold on, let me grab it.

https://github.com/peardox/MakeP4DComponents

Special thanks to @peardox

**Comment by kazuser** [comment]
Thank you, I'll try :)

I hope (I'm lucky and) everything works out)))

**Comment by kazuser** [comment]
![image](https://github.com/Embarcadero/Lightweight-Python-Wrappers/assets/3335273/5d9e5b31-d81a-47f7-acad-b571b9537beb)

😊

Thanks again!
