### ISSUE TITLE
ModuleNotFoundError :(

### ISSUE THREAD

**Issue by kazuser** [Embarcadero/Lightweight-Python-Wrappers#21]
I think I need your help again: I created a "Lingua" component based on https://pypi.org/project/lingua-language-detector/ — and it works fine (languages are detected correctly) but the very first launch always fails:

> ModuleNotFoundError: No module named 'lingua-language-detector'

![Lingua](https://github.com/Embarcadero/Lightweight-Python-Wrappers/assets/3335273/35db19f7-ac38-4ed0-99fe-b7876eee9253)

How can it be fixed? 🥲

p.s.
[Lingua.zip](https://github.com/Embarcadero/Lightweight-Python-Wrappers/files/12138722/Lingua.zip)
[Project1.zip](https://github.com/Embarcadero/Lightweight-Python-Wrappers/files/12138724/Project1.zip)
[p4d.zip](https://github.com/Embarcadero/Lightweight-Python-Wrappers/files/12138726/p4d.zip)

**Comment by kazuser** [comment]
Please, guys, help me. This is the only library capable of more or less correctly detecting the language of super-short texts 🥲

**Comment by lmbelo** [comment]
Hmmm... I really think you didn't fix it right. You have tried to load a module that doesn't exist and then you only created a fake module using the TPythonModule component. You certainly will be caught by other erros while loading symbols from that module... I'd suggest you to re-check your _Lingua_ version or else if you have defined the right module name.

**Comment by lmbelo** [comment]
That package itself is called _lingua-language-detector_. I presume you're not importing it.
Here's how you can import your module: https://github.com/Embarcadero/Lightweight-Python-Wrappers/blob/37035df09e5775ac107b3dbba6f52552d2281614/src/PyCommon.pas#L137

**Comment by kazuser** [comment]
Thanks a lot, lmbelo!

You're right, it works!

![image](https://github.com/Embarcadero/Lightweight-Python-Wrappers/assets/3335273/73ea6b1e-e62c-44f2-b9cc-8cdebf3c3168)

😊
